name: Build and deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'apiBackEndGH'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BBC9D1B787A2478C83A757FC7666AD7B }}
          package: ./dist